/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class catnemo_top_glcore_GLCore */

#ifndef _Included_catnemo_top_glcore_GLCore
#define _Included_catnemo_top_glcore_GLCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     catnemo_top_glcore_GLCore
 * Method:    init
 * Signature: (Ljavax/microedition/khronos/egl/EGLContext;ILandroid/view/Surface;)Z
 */
JNIEXPORT jboolean JNICALL Java_catnemo_top_glcore_GLCore_init(JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     catnemo_top_glcore_GLCore
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_catnemo_top_glcore_GLCore_release
        (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
